# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\12284\Desktop\GitHub\ImageAnalysis\DesignerUI\Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 400)
        Form.setMinimumSize(QtCore.QSize(300, 400))
        Form.setMaximumSize(QtCore.QSize(300, 400))
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 30, 121, 111))
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\12284\\Desktop\\GitHub\\ImageAnalysis\\DesignerUI\\../images/rocket_48x48.png"))
        self.label.setScaledContents(True)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.login_name = QtWidgets.QLineEdit(Form)
        self.login_name.setGeometry(QtCore.QRect(40, 180, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Candara Light")
        font.setPointSize(10)
        self.login_name.setFont(font)
        self.login_name.setStyleSheet("border-color: rgb(81, 244, 244);\n"
"border: 2px solid #55ffff;\n"
"border-radius: 10px;\n"
"padding: 0 8px;")
        self.login_name.setText("")
        self.login_name.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.login_name.setCursorPosition(0)
        self.login_name.setDragEnabled(True)
        self.login_name.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.login_name.setClearButtonEnabled(True)
        self.login_name.setObjectName("login_name")
        self.login_password = QtWidgets.QLineEdit(Form)
        self.login_password.setGeometry(QtCore.QRect(40, 230, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Candara Light")
        font.setPointSize(10)
        self.login_password.setFont(font)
        self.login_password.setStyleSheet("border-color: rgb(81, 244, 244);\n"
"border: 2px solid #55ffff;\n"
"border-radius: 10px;\n"
"padding: 0 8px;")
        self.login_password.setText("")
        self.login_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.login_password.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.login_password.setClearButtonEnabled(True)
        self.login_password.setObjectName("login_password")
        self.login_in = QtWidgets.QPushButton(Form)
        self.login_in.setGeometry(QtCore.QRect(40, 290, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Candara Light")
        font.setPointSize(10)
        self.login_in.setFont(font)
        self.login_in.setStyleSheet("background-color: #55ffff;\n"
"border: 1px solid #55ffff;\n"
"border-radius: 10px;\n"
"padding: 0 8px;")
        self.login_in.setObjectName("login_in")
        self.login_register = QtWidgets.QPushButton(Form)
        self.login_register.setGeometry(QtCore.QRect(40, 340, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Candara Light")
        font.setPointSize(10)
        self.login_register.setFont(font)
        self.login_register.setStyleSheet("background-color: #55ffff;\n"
"border: 1px solid #55ffff;\n"
"border-radius: 10px;\n"
"padding: 0 8px;")
        self.login_register.setObjectName("login_register")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "LOGIN"))
        self.login_name.setPlaceholderText(_translate("Form", " input your name"))
        self.login_password.setPlaceholderText(_translate("Form", " input password"))
        self.login_in.setText(_translate("Form", "Login"))
        self.login_register.setText(_translate("Form", "Register"))
